plan vmware_tasks::vm_list(
  String $vsphere_host = '',
  String $vsphere_api_keyfile = '~/.vsphere_api_key',
  String $allow_insecure_ssl = false,
) {

# List VMs

# Get host
if ($vsphere_host == '') {
  $host = prompt('vSphere Host', 'default'=>$vsphere_host)
} else {
  $host = $vsphere_host
}

#Setup curl command as a variable for secure/insecure SSL
  if ($allow_insecure_ssl) { $curl='/usr/bin/curl -k' } else { $curl='/usr/bin/curl' }

#Load API Key generated by vmware_tasks::auth plan
$api_key = run_command("cat ${vsphere_api_keyfile}", localhost, 'Read API Key from file (please use vmware_tasks::auth plan to create).')[0].value['merged_output'] #lint:ignore:140chars



$result = run_command("${curl} -s -H \"vmware-api-session-id: ${api_key}\" https://${host}/api/vcenter/vm | jq", localhost)
#run_command("echo ${result[0].value['stdout']} | jq", localhost)
out::message($result[0].value['stdout'])

}
